export default {
  'ECOMM-404': {
    name: 'ECOMM-404',
    external: 'Not found',
    internal: 'Not found',
    status: 404,
  },
  'ECOMM-500': {
    name: 'ECOMM-500',
    external: 'Sorry something went wrong',
    internal: 'Internal server error, check previous logs with correlationId',
    status: 500,
  },
  'ECOMM-030': {
    name: 'ECOMM-030',
    external: 'Unable to find related articles.',
    internal: 'Failed retrieving articles',
    status: 404,
  },
  'ECOMM-029': {
    name: 'ECOMM-029',
    external: 'Could not find Article by slug',
    internal: 'Failed retrieving article',
    status: 404,
  },
  'ECOMM-028': {
    name: 'ECOMM-028',
    external: 'Cannot save a locked module',
    internal: 'User attempted to save a locked module',
    status: 400,
  },
  'ECOMM-027': {
    name: 'ECOMM-027',
    external: 'A failure occurred while fetching price range',
    internal: 'Failed retrieving priceRange',
    status: 500,
  },
  'ECOMM-026': {
    name: 'ECOMM-026',
    external: 'Cannot save a locked curation',
    internal: 'User attempted to save a locked curation',
    status: 400,
  },
  'ECOMM-025': {
    name: 'ECOMM-025',
    external: 'Module name already exists',
    internal: 'Error while creating a module with a given name',
    status: 400,
  },
  'ECOMM-024': {
    name: 'ECOMM-024',
    external: 'Sorry something went wrong',
    internal: 'Error while pulling the a module by id',
    status: 500,
  },
  'ECOMM-023': {
    name: 'ECOMM-023',
    external: 'A fail occured while loading modules',
    internal: 'Error while fetching the module list',
    status: 500,
  },
  'ECOMM-022': {
    name: 'ECOMM-022',
    external: 'A failure occurred while purging curations',
    internal: 'purgeCurations failed',
  },
  'ECOMM-021': {
    name: 'ECOMM-021',
    external: 'Failed to search for articles, try again',
    internal: 'searchArticles failed',
    status: 400,
  },
  'ECOMM-020': {
    name: 'ECOMM-020',
    external: 'Failed to scrape external link, try again',
    internal: 'Scraping an external link failed',
    status: 400,
  },
  'ECOMM-019': {
    name: 'ECOMM-019',
    external: 'Curation route was invalid',
    internal: 'Error while creating a curation with an invalid route',
    status: 400,
  },
  'ECOMM-018': {
    name: 'ECOMM-018',
    external: 'Sorry something went wrong',
    internal: 'Error while pulling a curation by route/brand',
    status: 500,
  },
  'ECOMM-017': {
    name: 'ECOMM-017',
    external: 'Sorry something went wrong',
    internal: 'Error while pulling the a curation by id',
    status: 500,
  },
  'ECOMM-016': {
    name: 'ECOMM-016',
    external: 'Sorry something went wrong',
    internal: 'Error while fetching the curations list',
    status: 500,
  },
  'ECOMM-015': {
    name: 'ECOMM-015',
    external: 'Sorry something went wrong',
    internal: 'Hot Read Article not found while pulling Article API',
    status: 500,
  },
  'ECOMM-014': {
    name: 'ECOMM-014',
    external: 'Sorry something went wrong',
    internal: 'Hot Reads not found while pulling API',
    status: 500,
  },
  'ECOMM-013': {
    name: 'ECOMM-013',
    external: 'Sorry something went wrong',
    internal: 'Filmstrip not found while pulling API',
    status: 500,
  },
  'ECOMM-012': {
    name: 'ECOMM-012',
    external: 'Sorry something went wrong',
    internal: 'River not found while pulling API',
    status: 500,
  },
  'ECOMM-011': {
    name: 'ECOMM-011',
    external: 'Not found',
    internal: 'Video not found while searching for video by id',
    status: 404,
  },
  'ECOMM-010': {
    name: 'ECOMM-010',
    external: 'Sorry something went wrong',
    internal: 'Error while finding video by id, check previous logs with correlationId',
    status: 500,
  },
  'ECOMM-009': {
    name: 'ECOMM-009',
    external: 'Not found',
    internal: 'Missing field required for article',
    status: 500,
  },
  'ECOMM-008': {
    name: 'ECOMM-008',
    external: 'Not found',
    internal: 'A video included with article was not found in video api.',
    status: 404,
  },
  BAD_URL: {
    external: 'Something went wrong with grabbing data from that URL',
    status: 500,
  },
  'ECOMM-007': {
    name: 'ECOMM-007',
    external: 'Sorry something went wrong',
    internal: 'Mongoose has failed reconnecting to  mongo.',
    status: 500,
  },
  'ECOMM-006': {
    name: 'ECOMM-006',
    external: 'Sorry something went wrong',
    internal: 'Mongoose has reconnected to  mongo.',
    status: 500,
  },
  'ECOMM-005': {
    name: 'ECOMM-005',
    external: 'Sorry something went wrong',
    internal: 'A call to get oembed data has failed, check previous logs with correlationId for more details',
    status: 500,
  },
  'ECOMM-004': {
    name: 'ECOMM-004',
    external: 'Sorry something went wrong',
    internal: ' mongo initial database connection has failed!',
    status: 500,
  },
  'ECOMM-003': {
    name: 'ECOMM-003',
    external: 'Sorry something went wrong',
    internal:
      'A call getting related videos has failed, check previous logs with correlationId for more details',
    status: 500,
  },
  'ECOMM-002': {
    name: 'ECOMM-002',
    external: 'Sorry something went wrong',
    internal:
      'A call getting related articles has failed, check previous logs with correlationId for more details',
    status: 500,
  },
  'ECOMM-001': {
    name: 'ECOMM-001',
    external: 'Sorry something went wrong',
    internal: 'Call to mongo has failed, check previous logs with correlationId for more details',
    status: 500,
  },
};
